# Form implementation generated from reading ui file 'src/ui/settingswindow.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(400, 267)
        SettingsWindow.setMinimumSize(QtCore.QSize(285, 215))
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBoxGames = GameComboBox(SettingsWindow)
        self.comboBoxGames.setObjectName("comboBoxGames")
        self.verticalLayout.addWidget(self.comboBoxGames)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(SettingsWindow)
        self.label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditPath = QtWidgets.QLineEdit(SettingsWindow)
        self.lineEditPath.setReadOnly(True)
        self.lineEditPath.setObjectName("lineEditPath")
        self.horizontalLayout.addWidget(self.lineEditPath)
        self.pushButtonBrowse = QtWidgets.QPushButton(SettingsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBrowse.sizePolicy().hasHeightForWidth())
        self.pushButtonBrowse.setSizePolicy(sizePolicy)
        self.pushButtonBrowse.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonBrowse.setObjectName("pushButtonBrowse")
        self.horizontalLayout.addWidget(self.pushButtonBrowse)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelHelp = QtWidgets.QLabel(SettingsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHelp.sizePolicy().hasHeightForWidth())
        self.labelHelp.setSizePolicy(sizePolicy)
        self.labelHelp.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelHelp.setObjectName("labelHelp")
        self.verticalLayout.addWidget(self.labelHelp)
        self.listView = QtWidgets.QListView(SettingsWindow)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonAdd = QtWidgets.QPushButton(SettingsWindow)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.horizontalLayout_2.addWidget(self.pushButtonAdd)
        self.pushButtonRename = QtWidgets.QPushButton(SettingsWindow)
        self.pushButtonRename.setEnabled(False)
        self.pushButtonRename.setObjectName("pushButtonRename")
        self.horizontalLayout_2.addWidget(self.pushButtonRename)
        self.pushButtonDelete = QtWidgets.QPushButton(SettingsWindow)
        self.pushButtonDelete.setEnabled(False)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.horizontalLayout_2.addWidget(self.pushButtonDelete)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "yassam - Settings"))
        self.label.setText(_translate("SettingsWindow", "Savefile Location"))
        self.pushButtonBrowse.setText(_translate("SettingsWindow", "..."))
        self.labelHelp.setText(_translate("SettingsWindow", "TextLabel"))
        self.pushButtonAdd.setText(_translate("SettingsWindow", "Add"))
        self.pushButtonRename.setText(_translate("SettingsWindow", "Rename"))
        self.pushButtonDelete.setText(_translate("SettingsWindow", "Delete"))
from widgets.gamecombobox import GameComboBox
