# Form implementation generated from reading ui file 'src/ui/settingswindow.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(400, 267)
        SettingsWindow.setMinimumSize(QtCore.QSize(285, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBoxGames = QtWidgets.QComboBox(SettingsWindow)
        self.comboBoxGames.setObjectName("comboBoxGames")
        self.verticalLayout.addWidget(self.comboBoxGames)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditPath = QtWidgets.QLineEdit(SettingsWindow)
        self.lineEditPath.setObjectName("lineEditPath")
        self.horizontalLayout.addWidget(self.lineEditPath)
        self.pushButtonBrowse = QtWidgets.QPushButton(SettingsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBrowse.sizePolicy().hasHeightForWidth())
        self.pushButtonBrowse.setSizePolicy(sizePolicy)
        self.pushButtonBrowse.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonBrowse.setObjectName("pushButtonBrowse")
        self.horizontalLayout.addWidget(self.pushButtonBrowse)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listWidgetProfiles = QtWidgets.QListWidget(SettingsWindow)
        self.listWidgetProfiles.setObjectName("listWidgetProfiles")
        self.verticalLayout.addWidget(self.listWidgetProfiles)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonNew = QtWidgets.QPushButton(SettingsWindow)
        self.pushButtonNew.setObjectName("pushButtonNew")
        self.horizontalLayout_2.addWidget(self.pushButtonNew)
        self.pushButtonDelete = QtWidgets.QPushButton(SettingsWindow)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.horizontalLayout_2.addWidget(self.pushButtonDelete)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "yassam - Settings"))
        self.pushButtonBrowse.setText(_translate("SettingsWindow", "..."))
        self.pushButtonNew.setText(_translate("SettingsWindow", "New"))
        self.pushButtonDelete.setText(_translate("SettingsWindow", "Delete"))
